/// Flutter icons GloveIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  GloveIcon
///      fonts:
///       - asset: fonts/GloveIcon.ttf
///
///
///
import 'package:flutter/widgets.dart';

class GloveIcon {
  GloveIcon._();

  static const _kFontFam = 'GloveIcon';
  static const String _kFontPkg = null;

  static const IconData glove =
      IconData(0xeba4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
